version: "3"
services:
    app:
        build:
            context: .
            target: prod
        environment:
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - DB_PORT=5432
            - DB_NAME=horizon

    db:
        container_name: 'horizondb'
        image: postgres:16-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - 5432:5432
        volumes:
            - horizon-db:/var/lib/postgresql/data
volumes:
    horizon-db:
        driver: local
